DROP TABLE IF EXISTS PRODUCT_LIST;

CREATE TABLE PRODUCT_LIST
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    GROUP_ID INT NOT NULL
);
INSERT INTO PRODUCT_LIST
VALUES (1, 'Cucumber', 1) ,
    (2, 'Apple', 2)
    ,
    (3, 'Orange', 2)
    ,
    (4, 'Strawberry',3);

DROP TABLE IF EXISTS PRODUCT_GROUP;

CREATE TABLE PRODUCT_GROUP
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
INSERT INTO PRODUCT_GROUP
VALUES (1, 'Vegetables') ,
    (2, 'Fruit')
    ,
    (3, 'Berry');

DROP TABLE IF EXISTS PRODUCT_COST;

CREATE TABLE PRODUCT_COST
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    COST    FLOAT,
    PRODUCT INT NOT NULL
);
INSERT INTO PRODUCT_COST
VALUES (1, '10.15', 1) ,
    (2, '20.15',2)
    ,
    (3, '120.15',3)
    ,
    (4, '320.15',4);

